### ISSUE TITLE
Please duplicate the 'New posts' link on the main page

### ISSUE THREAD

**Issue by sev-** [alexclemensua/scummvm-phpBB3-theme#11]
Current forums have a shortcut for the New posts link. In the new theme it is hidden under a drop-down menu.

Please duplicate them on the main page too:

<img width="498" alt="screen shot 2016-01-03 at 22 39 08" src="https://cloud.githubusercontent.com/assets/365188/12080913/d315870e-b26a-11e5-96d3-9ac9f1212470.png">

**Comment by alexclemensua** [comment]
![screen shot 2016-06-14 at 1 41 27 pm](https://cloud.githubusercontent.com/assets/3717248/16039981/b536da08-3235-11e6-9932-a731f77f7c8a.png)

**Comment by sev-** [comment]
nice
